
# Site settings
title: Meteci Testimoni 
email: lorenzo.molfetta9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
       "Presto ti accorgerai
       com'è facile farsi 
       un'inutile software di scienza."
       
       F. Guccini
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://LorMolf.github.io" # the base hostname & protocol for your site
twitter_username: Lorenzo_molf
github_username:  LorMolf


# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# sass:
# load_paths:
# - _sass


# Build settings
markdown: kramdown
kramdown:
        syntax_highlighter_opts:
                disable : true
        extensions: ["footnotes"]
permalink: pretty

# collections:
#         reti:
#                 output: true

highlighter: none

# # Where things are
# source              : .
# destination         : ./_site
# collections_dir     : .
# plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# sass:
#   sass_dir: _sass
# collections:
#   posts:
#     output          : true


# defaults:
#   -
#     scope:
#       type: post
#       path: _posts
#     values:
#       is_post: true
#       layout: post
#       future: true



# # Serving
# detach              : false
# port                : 4000
# host                : 127.0.0.1
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

# # Outputting
# permalink           : date
# paginate_path       : /page:num
# timezone            : null




